### ISSUE TITLE
Need to write tests

### ISSUE THREAD

**Issue by Itxaka** [pyapi-gitlab/pyapi-gitlab#1]
There is no tests for the whole thing.

**Comment by samrocketman** [comment]
[python unittest phony web server](http://stackoverflow.com/questions/2276689/how-do-i-unit-test-a-module-that-relies-on-urllib2)

After some light research I found that.

[Tests via setup.py](http://stackoverflow.com/questions/6891128/how-to-run-all-tests-in-a-setup-py-script)

**Comment by Itxaka** [comment]
Thanks you. Yeah I knew about creating phony service and libraries with mock objects but the thing is, I want to test the real thing, just in case the apis change and I miss it, the test would fail.

If there was an open gitlab around....like a demo or something from the gitlab guys it would be much easier.

**Comment by Itxaka** [comment]
Well, there actually is a demo gitlab from the gitlab makers :smile: 
http://demo.gitlabhq.com/

I think I can work with that :+1:
