### ISSUE TITLE
Add 'can_create_group' option to createuser() method

### ISSUE THREAD

**Issue by megatron-uk** [pyapi-gitlab/pyapi-gitlab#102]
It's just a missing parameter compared to the latest Gitlab API - I'm batch adding hundreds of our internal staff and student users to Gitlab and don't want all of them to have the ability to create new groups!

Here's a patch output from my own locally modified copy of pyapi-gitlab/**init**.py: https://gist.github.com/megatron-uk/fb12b1d290a2f32fcb5c

It's just two lines in the createuser() method.

**Comment by Itxaka** [comment]
Hi there,

this should have been fixed on commit: https://github.com/Itxaka/pyapi-gitlab/commit/af393b92c80045071569efb7f883295eea036e05

as we moved from using named parameters to just **kwargs, so you can pass the parameter can_create_group to the createuser() method and it should work.

Wont close this until I got a couple of tests working for this.

**Comment by Itxaka** [comment]
Tests are on  commit https://github.com/Itxaka/pyapi-gitlab/commit/a29b6beb291ab1d5cbd0f9bbe222dfdd81e6f6c8

Closing this, thanks for the heads up!
