### ISSUE TITLE
createproject() in the given group

### ISSUE THREAD

**Issue by Slaitt** [pyapi-gitlab/pyapi-gitlab#106]
Hi, 

I have a very simple problem when creating a project. I would like to create the project in the given group, but I don't see this option in the list of arguments for createproject() function. 

When I create a project it is created in my namespace say Administrator/. How can I move it to the group foo? I tried to use the function git.moveproject(groupID, projectID), but I can't get the project ID, as it is not visible when using function git.getprojects(), although I see it created in my namespace via gitlab web interface. So how I can get the projectID of the project created with createproject or create it the given group? Thank you for any hint.

**Comment by Itxaka** [comment]
Hello there,

the parameter you are looking for is namespace_id. From gitlab API documentation:
`namespace_id (optional) - namespace for the new project (defaults to user)`

So if you create your project with createproject(name="whatever", namespace_id=34534) it should work.

Also, when creating a project, the return value is a dictionary containing all the data from the new project, so you could use that to get the project id like this:

```
project = git.createproject(name="whatever")
print project["id"]
```

**Comment by Slaitt** [comment]
Hello, 

Great! Thank you. I had to look into the code. Actually I just took a quick look at http://pyapi-gitlab.readthedocs.org/en/6.1/#projects. Thanks for last hint, otherwise I did a loop over all projects to match the name and extract the id.
