### ISSUE TITLE
Too generic test paths

### ISSUE THREAD

**Issue by bdrung** [pyapi-gitlab/pyapi-gitlab#107]
I got a bug report for the pyapi-gitlab Debian package:

> python-gitlab and python3-gitlab respectively ship the overly generic paths `/usr/lib/python2.7/dist-packages/tests/__init__.py` and `/usr/lib/python3/dist-packages/tests/__init__.py`, leading to de facto conflicts with similarly broken packages.  Please either install these tests somewhere less likely to cause trouble or omit them altogether.

Please move the tests into the the gitlab namespace by putting them into the `gitlab` directory or adding `gitlab_` as prefix or similar.

**Comment by Itxaka** [comment]
Welp, good catch. As I didn't build any packages for it before, didn't thought of that but you are totally right, this is quite a problem!

On it!
