### ISSUE TITLE
updatemergerequest not according to spec

### ISSUE THREAD

**Issue by akariv** [pyapi-gitlab/pyapi-gitlab#108]
According to this:
http://doc.gitlab.com/ce/api/merge_requests.html#update-mr

updatemergerequest 
1. should be using the "PUT" HTTP method (instead of POST)
2. should be expecting the 200 status code (instead of 201)

**Comment by Itxaka** [comment]
Good catch, i been working on cleaning up the merge part of the lib so this issue comes on handy.

**Comment by Itxaka** [comment]
Fixed in https://github.com/Itxaka/pyapi-gitlab/commit/56d50fbf96cd36d5b0d3e5b966db9b3eb6eb363f

Thanks for the report!
