### ISSUE TITLE
Get Labels API doesn't have pagination but pyapi `getlabels` does

### ISSUE THREAD

**Issue by aneroid** [pyapi-gitlab/pyapi-gitlab#117]
Hi,

According to the GitLab docs, [Get/List Labels](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/labels.md#list-labels) does not have any pagination. However, [this API does](http://pyapi-gitlab.readthedocs.org/en/latest/#gitlab.Gitlab.getlabels) and has the `page` and `per_page` params. GitLab seems to ignore the extra params and keeps returning the full list of labels. So when `getlabels` is called with `page=2`, it still returns the full list,  even with `per_page=1`.

Note that in a GitLab project Labels web page, it does paginate by 20 but via the API, it remains un-paginated and returns the whole list.

**Comment by Itxaka** [comment]
Good catch, probably from the old api docs? Ill remove it.

**Comment by Itxaka** [comment]
Fixed on https://github.com/Itxaka/pyapi-gitlab/commit/241c32e3e00af6b0ace3b6e86a46d406733ad46f
