### ISSUE TITLE
push latest to pypi

### ISSUE THREAD

**Issue by solomongifford** [pyapi-gitlab/pyapi-gitlab#118]
The latest on https://pypi.python.org/pypi/pyapi-gitlab is broken for python 2.6.6 due to https://github.com/Itxaka/pyapi-gitlab/pull/111.

Can we get pypi updated?

**Comment by Itxaka** [comment]
will update today with a new version wich fixes many things :D

**Comment by Itxaka** [comment]
Latest version pushed to pypi!
