### ISSUE TITLE
ValueError: zero length field name in format

### ISSUE THREAD

**Issue by packadal** [pyapi-gitlab/pyapi-gitlab#120]
Hi, the main page says that python 2.6 is supported, however after installing using `pip install pyapi-gitlab=="7.5.0"` I get the following error : `ValueError: zero length field name in format` when calling `getmergerequests`, which seems to indicate it is python 3+.

Is python 2.6 supported and I made a mistake, or should the doc be updated ?

Thanks.

**Comment by Itxaka** [comment]
Should be supported thanks to a patch from @pminakov on https://github.com/Itxaka/pyapi-gitlab/pull/111

Let me have a look at it

**Comment by packadal** [comment]
it seems that this was merged _after_ the current release on pypi as stated in #118.

**Comment by Itxaka** [comment]
True! Ill still will make the runs work on 2.6 again, then upload the new version to pypi

**Comment by packadal** [comment]
Awesome ! Thanks :+1:

**Comment by Itxaka** [comment]
New version is uploaded. Unfortunately Im having issues with the testing on 2.6 but I tried it locally and it seems to work. Let me know if you encounter any issues while running it on 2.6.

Thanks!

**Comment by packadal** [comment]
I just gave it a try, and as far as I'm concerned this seems to work pretty well.

THanks a lot !
