### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by jirihnidek** [pyapi-gitlab/pyapi-gitlab#13]
Hi,
I strongly recommend to split **init**.py to several files. It would be also more logical to have several classes for Projects, Hooks, Groups, etc.

BTW: your pylint rating is very low: 3.69/10

Cheers,

Jiri

**Comment by Itxaka** [comment]
Hi there!

I fixed the > 80 chars lines and that got the pylint score up to 5.78. Still, Im not convinced as it makes the code much more unreadable.

Regarding the rest, it would involve changing a lot of variables which I find kind of time consuming but I could do it...with time :D

A couple of things more, splitting init into several files, could you explain the logic in that? I wanted python-gitlab to be the one-stop for using gitlab from python and I believe it's quite small and without too much dependencies, so splitting it into several files would go against the simplicity of it.

And clasess, the same. Why have several classes diferentiated when you could have it all under the same, small, easy umbrella?

Take into consideration that Im a beginner on python, so I could be missing something important on this :D

Thanks again!

**Comment by jirihnidek** [comment]
Hi,
pylint could be configured. The long lines is small mistake :-). On the other side there is something called PEP8 and it is very strong convention in Python community: http://www.python.org/dev/peps/pep-0008/. Variables called 'r' are not descriptive and camelCase function naming isn't used in most Python modules. If you do not have good reason to use camelCase (autogenerated binary module, backward compatibility), then you should follow PEP8.

Good code is testable. Testable code should be split in small files that can be tested with unit tests. Your code will be growing and growing. You probably aware that you still can't do many thing with gitlab module. You use two modules, right. Look at them. The requests and markdown modules are good examples, how to write code in Python.

You are welcome,

Jiri

**Comment by Itxaka** [comment]
pylint is now at 9.65 :cat: !

Will try to slit it in several submodules for the future.

Thanks!

**Comment by jirihnidek** [comment]
Great :+1: . You should update documentation to your module. :-)
