### ISSUE TITLE
how to disable ssl warning ?

### ISSUE THREAD

**Issue by avyou** [pyapi-gitlab/pyapi-gitlab#138]
> > > git = gitlab.Gitlab("https://gitlab.host.com", token="t3cZabcceyy8RddzBY1b",verify_ssl=False)
> > > 
> > > print git.currentuser()["username"]
> > > /usr/lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
> > >   InsecureRequestWarning)
> > > root

how to Don't show the following warning:
 "/usr/lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)"

thanks!

**Comment by Itxaka** [comment]
Hey,

to disable the warning you have to set in your code at the top:

```
import requests
from requests.packages.urllib3.exceptions import InsecurePlatformWarning
requests.packages.urllib3.disable_warnings(InsecurePlatformWarning)
```
