### ISSUE TITLE
AttributeError: 'Gitlab' object has no attribute 'getmergerequestchanges'

### ISSUE THREAD

**Issue by avyou** [pyapi-gitlab/pyapi-gitlab#139]
hi,

my gitlab version is 7.4,  I use pyapi-gitlab API :
1 . >>> import gitlab
2.  >>> git = gitlab.Gitlab("https://gitlab.host.com",verify_ssl=False)
3.  >>> git.login(user='gitlab',password='123456')
/usr/lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
True

then, git merge request:
1. > > >  git.createmergerequest('44','develop','master','this is a test')
   > > > /usr/lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
   > > > InsecureRequestWarning)
   > > > {u'downvotes': 0, u'target_branch': u'master', u'description': None, u'title': u'this is a test', u'created_at': u'2015-05-03T13:51:13.419+08:00', u'source_branch': u'develop', u'updated_at': u'2015-05-03T13:51:13.419+08:00', u'labels': [], u'iid': 17, u'state': u'opened', u'assignee': None, u'author': {u'username': u'gitlab', u'state': u'active', u'avatar_url': u'https://secure.gravatar.com/avatar/4160ab6efe7636cc4e576a4c47b40032?s=40&d=identicon', u'name': u'\u7ba1\u7406\u5458', u'id': 3}, u'milestone': None, u'upvotes': 0, u'target_project_id': 44, u'project_id': 44, u'id': 574, u'source_project_id': 44}
2. > > >  git.getmergerequestchanges('44','574')
   > > > Traceback (most recent call last):
   > > > File "<stdin>", line 1, in <module>
   > > > AttributeError: 'Gitlab' object has no attribute 'getmergerequestchanges'

why AttributeError ? please help me thanks!

**Comment by avyou** [comment]
I update gitlab to 7-8, it is ok! thanks

**Comment by avyou** [comment]
sorry, It still did not work.

I use linux curl  command is ok:

curl --header "PRIVATE-TOKEN: t3cZ5R7zzz8Rt-zzBYsb" "http://gitlab.host.com/api/v3/projects/44/merge_request/574/changes"

{"id":574,"iid":17,"project_id":44,"title":"this is a test","description":null,"state":"opened","created_at":"2015-05-03T05:51:13.000Z","updated_at":"2015-05-03T05:51:24.000Z","target_branch":"master","source_branch":"develop","upvotes":0,"downvotes":0,"author":{"name":"管理员","username":"gitlab","id":3,"state":"active","avatar_url":"http://gitlab.usport.cc/uploads/user/avatar/3/2-2.jpg"},"assignee":null,"source_project_id":44,"target_project_id":44,"labels":[],"milestone":null,"changes":[{"old_path":"123.txt","new_path":"123.txt","a_mode":"100644","b_mode":"0","diff":"--- a/123.txt\n+++ /dev/null","new_file":false,"renamed_file":false,"deleted_file":true},{"old_path":"abc.txt","new_path":"abc.txt","a_mode":"100644","b_mode":"100644","diff":"--- a/abc.txt\n+++ b/abc.txt\n@@ -1 +1 @@\n-123\n\\ No newline at end of file\n+abc\n\\ No newline at end of file","new_file":false,"renamed_file":false,"deleted_file":false},{"old_path":"test3.txt","new_path":"test3.txt","a_mode":"0","b_mode":"100644","diff":"--- /dev/null\n+++ b/test3.txt","new_file":true,"renamed_file":false,"deleted_file":false},{"old_path":"test4.txt","new_path":"test4.txt","a_mode":"0","b_mode":"100644","diff":"--- /dev/null\n+++ b/test4.txt","new_file":true,"renamed_file":false,"deleted_file":false}]}

but use pyapi-gitlab return no attribute error :
>>> git = gitlab.Gitlab("http://gitlab.host.com")
>>> git.login(user='gitlab',password='123456')
True
>>> git.getmergerequestchanges('44','574')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Gitlab' object has no attribute 'getmergerequestchanges'

why ?
Now gitlab version is 7-8.

**Comment by avyou** [comment]
sorry, It still did not work.

I use linux curl  command is ok:

curl --header "PRIVATE-TOKEN: t3cZ5R7zzz8Rt-zzBYsb" "http://gitlab.host.com/api/v3/projects/44/merge_request/574/changes"

{"id":574,"iid":17,"project_id":44,"title":"this is a test","description":null,"state":"opened","created_at":"2015-05-03T05:51:13.000Z","updated_at":"2015-05-03T05:51:24.000Z","target_branch":"master","source_branch":"develop","upvotes":0,"downvotes":0,"author":{"name":"管理员","username":"gitlab","id":3,"state":"active","avatar_url":"http://gitlab.usport.cc/uploads/user/avatar/3/2-2.jpg"},"assignee":null,"source_project_id":44,"target_project_id":44,"labels":[],"milestone":null,"changes":[{"old_path":"123.txt","new_path":"123.txt","a_mode":"100644","b_mode":"0","diff":"--- a/123.txt\n+++ /dev/null","new_file":false,"renamed_file":false,"deleted_file":true},{"old_path":"abc.txt","new_path":"abc.txt","a_mode":"100644","b_mode":"100644","diff":"--- a/abc.txt\n+++ b/abc.txt\n@@ -1 +1 @@\n-123\n\\ No newline at end of file\n+abc\n\\ No newline at end of file","new_file":false,"renamed_file":false,"deleted_file":false},{"old_path":"test3.txt","new_path":"test3.txt","a_mode":"0","b_mode":"100644","diff":"--- /dev/null\n+++ b/test3.txt","new_file":true,"renamed_file":false,"deleted_file":false},{"old_path":"test4.txt","new_path":"test4.txt","a_mode":"0","b_mode":"100644","diff":"--- /dev/null\n+++ b/test4.txt","new_file":true,"renamed_file":false,"deleted_file":false}]}

but use pyapi-gitlab return no attribute error :
>>> git = gitlab.Gitlab("http://gitlab.host.com")
>>> git.login(user='gitlab',password='123456')
True
>>> git.getmergerequestchanges('44','574')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Gitlab' object has no attribute 'getmergerequestchanges'

why ?
Now gitlab version is 7-8.

**Comment by avyou** [comment]
sorry, It still did not work.

I use linux curl  command is ok:

curl --header "PRIVATE-TOKEN: t3cZ5R7zzz8Rt-zzBYsb" "http://gitlab.host.com/api/v3/projects/44/merge_request/574/changes"

{"id":574,"iid":17,"project_id":44,"title":"this is a test","description":null,"state":"opened","created_at":"2015-05-03T05:51:13.000Z","updated_at":"2015-05-03T05:51:24.000Z","target_branch":"master","source_branch":"develop","upvotes":0,"downvotes":0,"author":{"name":"管理员","username":"gitlab","id":3,"state":"active","avatar_url":"http://gitlab.usport.cc/uploads/user/avatar/3/2-2.jpg"},"assignee":null,"source_project_id":44,"target_project_id":44,"labels":[],"milestone":null,"changes":[{"old_path":"123.txt","new_path":"123.txt","a_mode":"100644","b_mode":"0","diff":"--- a/123.txt\n+++ /dev/null","new_file":false,"renamed_file":false,"deleted_file":true},{"old_path":"abc.txt","new_path":"abc.txt","a_mode":"100644","b_mode":"100644","diff":"--- a/abc.txt\n+++ b/abc.txt\n@@ -1 +1 @@\n-123\n\\ No newline at end of file\n+abc\n\\ No newline at end of file","new_file":false,"renamed_file":false,"deleted_file":false},{"old_path":"test3.txt","new_path":"test3.txt","a_mode":"0","b_mode":"100644","diff":"--- /dev/null\n+++ b/test3.txt","new_file":true,"renamed_file":false,"deleted_file":false},{"old_path":"test4.txt","new_path":"test4.txt","a_mode":"0","b_mode":"100644","diff":"--- /dev/null\n+++ b/test4.txt","new_file":true,"renamed_file":false,"deleted_file":false}]}

but use pyapi-gitlab return no attribute error :
>>> git = gitlab.Gitlab("http://gitlab.host.com")
>>> git.login(user='gitlab',password='123456')
True
>>> git.getmergerequestchanges('44','574')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Gitlab' object has no attribute 'getmergerequestchanges'

why ?
Now gitlab version is 7-8.

**Comment by avyou** [comment]
sorry, It still did not work.

I use linux curl  command is ok:

curl --header "PRIVATE-TOKEN: t3cZ5R7zzz8Rt-zzBYsb" "http://gitlab.host.com/api/v3/projects/44/merge_request/574/changes"

{"id":574,"iid":17,"project_id":44,"title":"this is a test","description":null,"state":"opened","created_at":"2015-05-03T05:51:13.000Z","updated_at":"2015-05-03T05:51:24.000Z","target_branch":"master","source_branch":"develop","upvotes":0,"downvotes":0,"author":{"name":"管理员","username":"gitlab","id":3,"state":"active","avatar_url":"http://gitlab.usport.cc/uploads/user/avatar/3/2-2.jpg"},"assignee":null,"source_project_id":44,"target_project_id":44,"labels":[],"milestone":null,"changes":[{"old_path":"123.txt","new_path":"123.txt","a_mode":"100644","b_mode":"0","diff":"--- a/123.txt\n+++ /dev/null","new_file":false,"renamed_file":false,"deleted_file":true},{"old_path":"abc.txt","new_path":"abc.txt","a_mode":"100644","b_mode":"100644","diff":"--- a/abc.txt\n+++ b/abc.txt\n@@ -1 +1 @@\n-123\n\\ No newline at end of file\n+abc\n\\ No newline at end of file","new_file":false,"renamed_file":false,"deleted_file":false},{"old_path":"test3.txt","new_path":"test3.txt","a_mode":"0","b_mode":"100644","diff":"--- /dev/null\n+++ b/test3.txt","new_file":true,"renamed_file":false,"deleted_file":false},{"old_path":"test4.txt","new_path":"test4.txt","a_mode":"0","b_mode":"100644","diff":"--- /dev/null\n+++ b/test4.txt","new_file":true,"renamed_file":false,"deleted_file":false}]}

but use pyapi-gitlab return no attribute error :
>>> git = gitlab.Gitlab("http://gitlab.host.com")
>>> git.login(user='gitlab',password='123456')
True
>>> git.getmergerequestchanges('44','574')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Gitlab' object has no attribute 'getmergerequestchanges'

why ?
Now gitlab version is 7-8.

**Comment by avyou** [comment]
sorry, It still did not work.

I use linux curl  command is ok:

curl --header "PRIVATE-TOKEN: t3cZ5R7zzz8Rt-zzBYsb" "http://gitlab.host.com/api/v3/projects/44/merge_request/574/changes"

{"id":574,"iid":17,"project_id":44,"title":"this is a test","description":null,"state":"opened","created_at":"2015-05-03T05:51:13.000Z","updated_at":"2015-05-03T05:51:24.000Z","target_branch":"master","source_branch":"develop","upvotes":0,"downvotes":0,"author":{"name":"管理员","username":"gitlab","id":3,"state":"active","avatar_url":"http://gitlab.usport.cc/uploads/user/avatar/3/2-2.jpg"},"assignee":null,"source_project_id":44,"target_project_id":44,"labels":[],"milestone":null,"changes":[{"old_path":"123.txt","new_path":"123.txt","a_mode":"100644","b_mode":"0","diff":"--- a/123.txt\n+++ /dev/null","new_file":false,"renamed_file":false,"deleted_file":true},{"old_path":"abc.txt","new_path":"abc.txt","a_mode":"100644","b_mode":"100644","diff":"--- a/abc.txt\n+++ b/abc.txt\n@@ -1 +1 @@\n-123\n\\ No newline at end of file\n+abc\n\\ No newline at end of file","new_file":false,"renamed_file":false,"deleted_file":false},{"old_path":"test3.txt","new_path":"test3.txt","a_mode":"0","b_mode":"100644","diff":"--- /dev/null\n+++ b/test3.txt","new_file":true,"renamed_file":false,"deleted_file":false},{"old_path":"test4.txt","new_path":"test4.txt","a_mode":"0","b_mode":"100644","diff":"--- /dev/null\n+++ b/test4.txt","new_file":true,"renamed_file":false,"deleted_file":false}]}

but use pyapi-gitlab return no attribute error :
>>> git = gitlab.Gitlab("http://gitlab.host.com")
>>> git.login(user='gitlab',password='123456')
True
>>> git.getmergerequestchanges('44','574')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Gitlab' object has no attribute 'getmergerequestchanges'

why ?
Now gitlab version is 7-8.

**Comment by avyou** [comment]
sorry, It still did not work.

I use linux curl  command is ok:

curl --header "PRIVATE-TOKEN: t3cZ5R7zzz8Rt-zzBYsb" "http://gitlab.host.com/api/v3/projects/44/merge_request/574/changes"

{"id":574,"iid":17,"project_id":44,"title":"this is a test","description":null,"state":"opened","created_at":"2015-05-03T05:51:13.000Z","updated_at":"2015-05-03T05:51:24.000Z","target_branch":"master","source_branch":"develop","upvotes":0,"downvotes":0,"author":{"name":"管理员","username":"gitlab","id":3,"state":"active","avatar_url":"http://gitlab.usport.cc/uploads/user/avatar/3/2-2.jpg"},"assignee":null,"source_project_id":44,"target_project_id":44,"labels":[],"milestone":null,"changes":[{"old_path":"123.txt","new_path":"123.txt","a_mode":"100644","b_mode":"0","diff":"--- a/123.txt\n+++ /dev/null","new_file":false,"renamed_file":false,"deleted_file":true},{"old_path":"abc.txt","new_path":"abc.txt","a_mode":"100644","b_mode":"100644","diff":"--- a/abc.txt\n+++ b/abc.txt\n@@ -1 +1 @@\n-123\n\\ No newline at end of file\n+abc\n\\ No newline at end of file","new_file":false,"renamed_file":false,"deleted_file":false},{"old_path":"test3.txt","new_path":"test3.txt","a_mode":"0","b_mode":"100644","diff":"--- /dev/null\n+++ b/test3.txt","new_file":true,"renamed_file":false,"deleted_file":false},{"old_path":"test4.txt","new_path":"test4.txt","a_mode":"0","b_mode":"100644","diff":"--- /dev/null\n+++ b/test4.txt","new_file":true,"renamed_file":false,"deleted_file":false}]}

but use pyapi-gitlab return no attribute error :
>>> git = gitlab.Gitlab("http://gitlab.host.com")
>>> git.login(user='gitlab',password='123456')
True
>>> git.getmergerequestchanges('44','574')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Gitlab' object has no attribute 'getmergerequestchanges'

Now gitlab version is 7-8.

**Comment by avyou** [comment]
sorry , my version issue. it is ok

**Comment by Itxaka** [comment]
Glad to know :)
