### ISSUE TITLE
Missing public option from createProject API call.

### ISSUE THREAD

**Issue by samrocketman** [pyapi-gitlab/pyapi-gitlab#14]
In the GitLab 6 API there is an [option](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/projects.md#create-project) for making a project `public` when it is created using `git.createProject()`.

**Comment by Itxaka** [comment]
Thank you! Fixed it, uploading it now. Thanks to this issue, now we can manage Gitlab 5 and 6 and add any extra options that version 6 has without having to heavily modify the code :D

**Comment by samrocketman** [comment]
Nice!  I'll test it out and let you know of my results from working with it :)

I'm using your project in my [gitlab-mirrors](https://github.com/sag47/gitlab-mirrors) project.  I'll make an update reflecting your API changes and I'll be adding SVN to it as well.  Thanks for the quick change!

**Comment by Itxaka** [comment]
Oooh, interesting project you got there. I'll check it out :D
