### ISSUE TITLE
How can I delete specific tag?

### ISSUE THREAD

**Issue by yukselao** [pyapi-gitlab/pyapi-gitlab#147]
How can I delete specific tag?

I checked out http://pyapi-gitlab.readthedocs.org/en/latest/ but can't see deletetag action on your documentation.

Kind regards

**Comment by Itxaka** [comment]
Hello @aliokanyuksel , I dont think the gitlab api supports deleting tags: http://doc.gitlab.com/ce/api/README.html

You can do it directly from the shell with git: https://nathanhoad.net/how-to-delete-a-remote-git-tag
