### ISSUE TITLE
Had trouble with setting options for createProject

### ISSUE THREAD

**Issue by samrocketman** [pyapi-gitlab/pyapi-gitlab#15]
https://github.com/gitlabhq/gitlab-recipes/issues/126

I was having trouble with setting new options for `git.createProject`.  I was passing options to the function as booleans like `True` and I even tried `str(True)`.  I found that the API is expecting a number such as `0` or `1` e.g. `public=1`.  I resolved that issue by writing `str(int(True))`.

Not sure if you care to modify anything as it wasn't _really_ a problem with your project.  But it might confuse developers trying to develop against the API with `python-gitlab`.  Perhaps it would be useful to add a documentation example for `git.createProject` where it is setting some options changing defaults.

**Comment by Itxaka** [comment]
Hi there! thanks for your feedback!

Im not sure I understand your problem, going by the documentation http://python-gitlab.readthedocs.org/ all the args to createProject() are strings so a simple:

git.createProject("new project", public="1")

Should work, I think.

Can you explain it further?

Im firing up a VM to install gitlab 6 and try the method to see if I can find the issue you are mentioning, will report back ASAP.

Cheers!
Itxaka.

**Comment by samrocketman** [comment]
Sure, I'm using [optparse](http://docs.python.org/2/library/optparse.html) for argument handling in a python 2.x script.  I'm setting options in the script like `--wiki` and `--issues`.

[My optparse](https://github.com/sag47/gitlab-mirrors/blob/public/lib/manage_gitlab_project.py#L21-L31) looks like the following:

```
parser = OptionParser()
parser.add_option("--issues",dest="issues",action="store_true",default=False)
parser.add_option("--wall",dest="wall",action="store_true",default=False)
parser.add_option("--merge",dest="merge",action="store_true",default=False)
parser.add_option("--wiki",dest="wiki",action="store_true",default=False)
parser.add_option("--snippets",dest="snippets",action="store_true",default=False)
parser.add_option("--public",dest="public",action="store_true",default=False)
parser.add_option("--create",dest="create",action="store_true",default=False)
parser.add_option("--delete",dest="delete",action="store_true",default=False)
parser.add_option("--desc",dest="desc",metavar="DESC",default=False)
(options,args) = parser.parse_args()
```

So I was creating a project like.....

```
new_project=git.createProject(pname,description=options.desc,issues_enabled=options.issues,wall_enabled=options.wall,merge_requests_enabled=options.merge,wiki_enabled=options.wiki,snippets_enabled=options.snippets,public=options.public)
```

Since I was passing a boolean it would be set as `True`.  Booleans didn't work so I converted to a string e.g. `str(options.merge)` to get `merge_requests_enabled="True"`.  Converting to a string didn't work so I first converted it to an integer and then to a string and it finally worked.  e.g. `str(int(options.merge))` to get `merge_requests_enabled="1"`.  With that working I changed my `new_project` command [to the following](https://github.com/sag47/gitlab-mirrors/blob/public/lib/manage_gitlab_project.py#L75).

```
new_project=git.createProject(pname,description=options.desc,issues_enabled=str(int(options.issues)),wall_enabled=str(int(options.wall)),merge_requests_enabled=str(int(options.merge)),wiki_enabled=str(int(options.wiki)),snippets_enabled=str(int(options.snippets)),public=str(int(options.public)))
```

**Comment by samrocketman** [comment]
https://github.com/Itxaka/python-gitlab/blob/master/gitlab/__init__.py#L267-L272

You could check for typing in your code and then auto convert it for the user passing the argument.  e.g.

```
import types
def convertType(val):
  if type(val) == types.BooleanType:
    val = str(int(val))
  elif type(val) == types.StringType and val == "True":
    val = str(int(bool(val)))
```

Utilize it like so...

```
    data = {"name": name, "description": convertType(description),
            "default_branch": convertType(default_branch),
            "issues_enabled": convertType(issues_enabled), 
            "wall_enabled": convertType(wall_enabled),
            "merge_requests_enabled": convertType(merge_requests_enabled),
            "wiki_enabled": convertType(wiki_enabled),
            "snippets_enabled": convertType(snippets_enabled)}
```

And do the same for the public value.  But again it's not that big of a deal.  If you add it to your documentation I think it should be enough and note that booleans don't work in your documentation.  Sometimes it's better to just document it.  However you want to handle it is fine with me.

**Comment by Itxaka** [comment]
Hi there,

I was thinking maybe instead of using all args as strings, change them to int, at least for values that only have those options. I mean, it makes no sense tu use strings when the value is gonna be 1 or 0/true or false, like in the case of public or xxxID

what do you think?

**Comment by samrocketman** [comment]
I didn't know that it would straight up handle `int`.  Yeah I'd say converting to just an `int` is better if `requests` can handle that.

**Comment by Itxaka** [comment]
I tried to change it, let me know if it works now :)
