### ISSUE TITLE
why getproject function's parameter can't be "namespace/project_name"?

### ISSUE THREAD

**Issue by scm20008** [pyapi-gitlab/pyapi-gitlab#161]
getproject(project_id)
Get info for a project identified by id or namespace/project_name

Parameters: project_id – id or namespace/project_name of the project
Returns:    False if not found, a dictionary if found

Question or Issue:
why getproject function's parameter can't be "namespace/project_name"?

**Comment by scm20008** [comment]
how to get project_id？

**Comment by ak0ska** [comment]
I'm just getting familiar with this library, but did you try [searchproject](http://pyapi-gitlab.readthedocs.org/en/latest/#gitlab.Gitlab.searchproject)?

**Comment by scm20008** [comment]
yes, I did. but the searchproject function doesn't work for me.

I wanna get project_id, I know the project_name, but every function needs the project_id as a parameter to run.

So how can I get project_id from project_name?

Thank you for your replying.

**Comment by scm20008** [comment]
and could you give me an example of searchproject function? thanks.

**Comment by scm20008** [comment]
Thanks, getprojects function has resolved my problem.

I can get project_id from project_name quickly by getprojects funcktion.
