### ISSUE TITLE
Status of gitlab 8.1 support

### ISSUE THREAD

**Issue by sotte** [pyapi-gitlab/pyapi-gitlab#165]
I was wondering about the support of gitlab 8.1. Are there any plans supporting it? Maybe it simply works already?

**Comment by Itxaka** [comment]
Hey @sotte !

Unfortunately with a change of job and the stupid decisions from https://github.com/gitlabhq on breaking the API on every minor release, I had no time to update or take care of testing the lib against every release nor add new features and try to maintain backwards compatibility.

I may work but it will probably behave wrongly. They probably changed the api AGAIN for some strange reason.

Regards,
Itxaka

**Comment by sotte** [comment]
@Itxaka, thanks for the quick response! That's bad news :( I'll give it a try. Maybe the basic stuff (creating users and project) works. Thanks!
