### ISSUE TITLE
getsshkeys() return bool instead of iterable: TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by ssbarnea** [pyapi-gitlab/pyapi-gitlab#170]
```
# using latest release pyapi-gitlab-7.8.5:
for member in git.getgroupmembers(g_id):
    user = member['username']
    print(user)
    git.setsudo(user)
    for key_dic in git.getsshkeys(): # here you get TypeError: 'bool' object is not iterable
       pass
```

I mention that the code works when the users do have ssh keys, the problem is when they do not have keys the function returns `False` instead of an empty list, which explains why we have this bug.

**Comment by Sudo-Kid** [comment]
The PR for this is closed and we will be updating this to use the new pattern in the future.
