### ISSUE TITLE
getgroupmembers() does not return iterable, returns bool instead

### ISSUE THREAD

**Issue by ssbarnea** [pyapi-gitlab/pyapi-gitlab#171]
getgroupmembers() does not return iterable, returns bool instead.

This is an anti-pattern in python and it seems not to happen only with this method call, but also with others and that's a critical issue: in python the rule is to return iterables for all things that can get multiple values. 

An empty list would still evaluate as False but it will be iterable!

**Comment by Sudo-Kid** [comment]
The PR for this was closed and this will be updated to follow a new pattern that is being implemented.
