### ISSUE TITLE
how to get the mergerequest_id?

### ISSUE THREAD

**Issue by scm20008** [pyapi-gitlab/pyapi-gitlab#175]
when I finished creating merge request, how can I get the mergerequest_id?

thanks!

**Comment by scm20008** [comment]
@Itxaka , Could you help me?

**Comment by solomongifford** [comment]
@scm20008,

When you call createmergerequest, it returns a json object that includes the id of the merge request.

```
results = createmergerequest(....)
print results['mergerequest']['iid']
```

**Comment by scm20008** [comment]
@solomongifford 

why I get a bool value as follows:

Traceback (most recent call last):
  File "gitlab/test_gitlab.py", line 17, in <module>
    print merge_request['mergerequest']['iid']
TypeError: 'bool' object has no attribute '**getitem**'

It doesn't return a dict value!

**Comment by solomongifford** [comment]
If the merge request was not created it returns False.

**Comment by scm20008** [comment]
It returns True, and I can get the result from the website of gitlab.

**Comment by scm20008** [comment]
@solomongifford 
the snapshot as follows:

![merge_request1](https://cloud.githubusercontent.com/assets/639305/12571033/072c10e4-c418-11e5-9f21-b522e918262b.png)
![merge_request2](https://cloud.githubusercontent.com/assets/639305/12571034/072f4502-c418-11e5-94ad-d08d473c8665.png)

**Comment by solomongifford** [comment]
The following is the latest code for createmergerequest - note that it does not return true.  I'm wondering if you have an old version of the library.

```
def createmergerequest(self, project_id, sourcebranch, targetbranch,
                           title, target_project_id=None, assignee_id=None):
        """Create a new merge request.
        :param project_id: ID of the project originating the merge request
        :param sourcebranch: name of the branch to merge from
        :param targetbranch: name of the branch to merge to
        :param title: Title of the merge request
        :param assignee_id: Assignee user ID
        :return: dict of the new merge request
        """
        data = {'source_branch': sourcebranch,
                'target_branch': targetbranch,
                'title': title,
                'assignee_id': assignee_id,
                'target_project_id': target_project_id}
        request = requests.post('{0}/{1}/merge_requests'.format(self.projects_url, project_id),
                                data=data, headers=self.headers, verify=self.verify_ssl, auth=self.auth, timeout=self.timeout)
        if request.status_code == 201:
            return request.json()
        else:
            return False
```

**Comment by scm20008** [comment]
@solomongifford 
Could you tell me how I can update the api version? thanks!

I use pyapi-gitlab 6.2.3.

**Comment by solomongifford** [comment]
I'll leave the updating of the package to the internet, but if you do:

```
pip show pyapi-gitlab
```

This will show the location where the package is installed.  Assuming its "/usr/lib/python2.6/site-packages/" open the file:

```
/usr/lib/python2.6/site-packages/gitlab/__init__.py
```

Look for the function createmergerequest and see if it matches the above.  If it does, you can do further debugging by adding print statements in the above mentioned function.

**Comment by scm20008** [comment]
thank @solomongifford ,
My problem had been resolved! I had updated the version to pyapi-gitlab 7.8.5, and now I can get the dict value.

thanks again!
