### ISSUE TITLE
How to acceptmergerequest after running createmergerequest?

### ISSUE THREAD

**Issue by scm20008** [pyapi-gitlab/pyapi-gitlab#176]
@solomongifford @Itxaka 
When I finished running createmergerequest function, I can't acceptmergerequest, Why?

but if I click the "accept merge request" button on the website of gitlab is OK.

thanks!

**Comment by scm20008** [comment]
@solomongifford @Itxaka 

and I search the source code of api:
print request.status_code, the result is 404. why?

**Comment by solomongifford** [comment]
You need the id for the acceptmergerequest, and the iid for the url.  Compare the two different id's and how gitlab uses them.

**Comment by scm20008** [comment]
@solomongifford 
my codes as follows:
`merge_request = git.createmergerequest(project_id, sourcebranch, targetbranch, title, None, None)`
`mergerequest_id = merge_request['iid']`
`accept_merge = git.acceptmergerequest(project_id, mergerequest_id, merge_commit_message)`

aren't my codes false?

**Comment by solomongifford** [comment]
See my previous comment @scm20008
