### ISSUE TITLE
Get the SSH keys of a user

### ISSUE THREAD

**Issue by ghost** [pyapi-gitlab/pyapi-gitlab#183]
Hi,

Is there any way to get the public SSH keys of a user?

Thank you.

Asher256

**Comment by Itxaka** [comment]
You could use http://pyapi-gitlab.readthedocs.org/en/latest/#gitlab.Gitlab.setsudo to change to the user (only if you are an admin) and then use http://pyapi-gitlab.readthedocs.org/en/latest/#gitlab.Gitlab.getsshkeys to get all the ssh keys for that user.

There is a api call to get ssh keys for an user but its not implemented in pyapi-gitlab https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/users.md#list-ssh-keys-for-user

**Comment by Sudo-Kid** [comment]
There has been no response to this answer for over a year and as such I will be closing it.
