### ISSUE TITLE
Requirements badge not active

### ISSUE THREAD

**Issue by gbraad** [pyapi-gitlab/pyapi-gitlab#186]
The badge provided by http://requires.io does currently not work:

[![Requirements Status](https://requires.io/github/Itxaka/pyapi-gitlab/requirements.svg?branch=develop)](https://requires.io/github/Itxaka/pyapi-gitlab/requirements/?branch=develop)

The namespace in the url still points to the project located at Ixtaka, but the new location is not activated for use with requires.

[![Requirements Status](https://requires.io/github/pyapi-gitlab/pyapi-gitlab/requirements.svg?branch=develop)](https://requires.io/github/Itxaka/pyapi-gitlab/requirements/?branch=develop)

**Comment by Sudo-Kid** [comment]
Updated.
