### ISSUE TITLE
Unhandled status codes with relevant excepions

### ISSUE THREAD

**Issue by ozbarshalom** [pyapi-gitlab/pyapi-gitlab#208]
All of the functions returns `False `if the http status code is not 200.
Functions should raise custom exceptions instead return `False`.

**Comment by Sudo-Kid** [comment]
I agree.

This though has a bigger question. How do you make a change like that without breaking everyone's current applications.

**Comment by ozbarshalom** [comment]
You will break everyone\`s code... That`s should be a major version
But. Without the exceptions, this whole library is pretty hard to use.
I found it the hard way, and I decided to move to [python-gitlab](https://github.com/gpocentek/python-gitlab) that have many exceptions

**Comment by Sudo-Kid** [comment]
I'm sorry to have lost you but I do understand why. I myself have run into that same problem with this library. I would though like to assure you that in the future we will have better error reporting. I only recently took over this project and there is some work to do before I start drastically changing the API.

**Comment by Sudo-Kid** [comment]
This issue is under active development at the moment and a repeat of issue https://github.com/pyapi-gitlab/pyapi-gitlab/issues/193.
