### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by Itxaka** [pyapi-gitlab/pyapi-gitlab#21]
update docs with the new features and args

**Comment by samrocketman** [comment]
If you want, I don't mind updating the documentation.  How would I go about doing that?

**Comment by Itxaka** [comment]
Hi Sam, thanks for the offering.

Do you know anything about sphinx? http://sphinx-doc.org/
It's like restructuredtext or markdown.

The file to modify is the index.rst in the docs/ directory.

Thanks again.

**Comment by Itxaka** [comment]
Docs are updated, but still missing the snippets part
