### ISSUE TITLE
Support getting all deploy keys

### ISSUE THREAD

**Issue by sijis** [pyapi-gitlab/pyapi-gitlab#213]
The library is currently able to get deploy keys that are enabled by a project.
There is currently no way to get a list of all available deploy keys.

This matters when someone wants to add a deploy key to a project.

I'm looking for this endpoint to be implemented (also supported by CE):
https://docs.gitlab.com/ee/api/deploy_keys.html#list-all-deploy-keys

**Comment by Sudo-Kid** [comment]
Thank you for bringing it up. I will add it to my list of things to work on.

**Comment by sijis** [comment]
@the-kid89 i'm actually putting together and PR for this, as we speak.

**Comment by Sudo-Kid** [comment]
Looking forward to it.

**Comment by Sudo-Kid** [comment]
https://github.com/pyapi-gitlab/pyapi-gitlab/pull/214
