### ISSUE TITLE
Support enabling deploy keys to projects

### ISSUE THREAD

**Issue by sijis** [pyapi-gitlab/pyapi-gitlab#216]
I'm unable to find a way to enable a deploy key for a specific project.

I'm essentially looking for this:
https://docs.gitlab.com/ee/api/deploy_keys.html#enable-a-deploy-key

**Comment by sijis** [comment]
I'm likely going to put a PR on it shortly.

**Comment by Sudo-Kid** [comment]
Looking forward to reviewing it.

**Comment by sijis** [comment]
I have a PR going #218, however I want to make sure that I add the test cases properly. I was trying out the `coverage run ...` that's in `.travis.yaml` but I doesn't seem to work.
How are you running the tests locally?

**Comment by Sudo-Kid** [comment]
You will want to make sure you do a `pip install -r test-requirements.txt`. If you are on a Unix like system that has bash installed you can just run `./cov` from the project root. I just added it in my most recent push.

The `.travis.yaml` file is outdated and shouldn't be used anymore. I'm still in the process of adding full integration tests to replace the old set. In the mean time I'm adding unittests with tested output.

Alternatively you can just run `coverage run -m unittest discover -s . && coverage html` from the project root.

**Comment by sijis** [comment]
Gotcha. I'll try it out when I get home.

I figured there was some refactoring going on as there were two sets of tests for the same stuff.

Are you hoping to reintegrate into Travis again?

**Comment by Sudo-Kid** [comment]
I do. Once we have 100% unittest coverage I plan to start adding integration tests. In the mean time I have been running all the tests with coverage locally.
