### ISSUE TITLE
Versions, tags and branches

### ISSUE THREAD

**Issue by samrocketman** [pyapi-gitlab/pyapi-gitlab#23]
You should take advantage of tags and branches.  You should also version your software and keep stability branches for each major version.  Similar to how @gitlabhq does it in their projects.  As fast as development is for GitLab I think it would be useful in case you need to completely refactor `python-gitlab` for a new version of GitLab you have a stable branch for previous versions of GitLab.  Just thinking ahead.  Tags would provide releases for people to download.  Since you don't take advantage of that I mention which commit ID to checkout in your project in my documentation because it's the only way to ensure that it works with that version since you don't use tags or branches.

[git-flow](http://nvie.com/posts/a-successful-git-branching-model/) is a popular workflow method which I like to use.  As part of that workflow ideally you should only accept pull requests which come from branches off of master.  Accepting `master` branch pull requests from forked projects is not a good workflow model and has the great potential of messing up your code base.  If you notice with each pull request I make to you it [comes from a branch](https://github.com/sag47/python-gitlab/network) off of `master` but not `master` itself.

**Comment by Itxaka** [comment]
Yeah, I got git pretty abandoned, I basically only use push, pull and... rebase sometimes. Will check that link.

Thank you :+1:

**Comment by samrocketman** [comment]
I'm going to close this.  I see you're finally starting use tags/branches :+1: :godmode:

**Comment by samrocketman** [comment]
@Itxaka You're kind of using branches differently than what I meant.  You're doing all of your development on the 6-1-stable branch and neglecting the other branches.  This is not much different than what I previously described.  It would be better for you to have a development branch for all development and only utilize the stable branch(s) for stable working commits only.

I'm attempting to develop off of your stable branch currently and it is highly unstable.

**Comment by Itxaka** [comment]
Yes, you are rigth. I started correctly but suddenly changed to work on 6.1  ranch only.

Will try to fix a couple of bugs, fill the documentatiin finally and set the final 6.1 stable branch and move everything to development in order to do a 6.2 stable release soon.

Cheers

**Comment by Itxaka** [comment]
Hey @sag47 , Inthink Im finally doing it correctly :D
developing on develop branch and when stable, creating branches for stable releases. What do you think?

**Comment by samrocketman** [comment]
That's better in my opinion.  One last thing though you don't need to change it if you don't want to is that your develop branch is the default branch. This means when people clone your repository they are getting development code and not stable code.

Not all projects develop the way I do for instance look at gitlabhq.  They develop on the master branch and then have stable branches for each release.  The stable branches and a proper tagging system is important though.

**Comment by Itxaka** [comment]
Yeah, I wasn't sure what to put as default, but I thougth that if the stable packages are at pypi, I guess people use pip to install them instead of cloning git repositories and such, so any developer that comes around can see full front the ongoing code instead.

**Comment by samrocketman** [comment]
@Itxaka That makes sense for you to use your model in that way.  In the case of my `gitlab-mirrors` project it's the opposite where the source to get the software is the git repository itself so for me stable releases on the default branch is to be desired.

**Comment by samrocketman** [comment]
Also since you use pip.  Your tags in the source repo should match the version number in pip.  As a python developer I would expect to be able to check out your source tree and then check out the exact version number displayed in pip to get the same version library from the source git repository.  That's why you see me using incremental tags (e.g. `v0.1.0`, `v0.1.1`, etc.) in my project.  This makes adding the next tag easy.

Any time you're deploying to pypi you should be tagging that sha1 with the same version number as in pypi.

**Comment by Leibniz137** [comment]
Could you please release a new version/tag and update pypi accordingly?

**Comment by Itxaka** [comment]
Yup!
