### ISSUE TITLE
nameclash with 'python-gitlab'

### ISSUE THREAD

**Issue by umlaeute** [pyapi-gitlab/pyapi-gitlab#263]
there's another project that provides access to the gitlab API for Python, named `python-gitlab`

    https://github.com/python-gitlab/python-gitlab

both this project and the other one use the same import name

~~~python
import gitlab
~~~

unfortunately, the two projects have a different API...

I don't really know nor care which of the two projects has a deeper claim on the name, but i'd suggest the two projects coordinate the namespace (most likely renaming *this*).

**Comment by umlaeute** [comment]
i've also opened a ticket on the "other" project: https://github.com/python-gitlab/python-gitlab/issues/385

**Comment by Sudo-Kid** [comment]
@umlaeute I'm with @gpocentek. This is a bad situation for both libs. I'm finding it really hard to get time for this project as is.

If we change the namespace it will negatively affect a Debian package as well as everyone that currently uses the lib. It would be like Debian changing the `python3-gitlab` package from this one to `python-gitlab`. It would affect businesses in a negative way that use the package/lib for there project.

Side note. I would do it if this project was just starting out.
