### ISSUE TITLE
sudo added to GitLab 6.1 API

### ISSUE THREAD

**Issue by samrocketman** [pyapi-gitlab/pyapi-gitlab#28]
GitLab 6.1 now has [sudo](https://github.com/gitlabhq/gitlabhq/tree/6-1-stable/doc/api#sudo) as an option.  I think it would be worth adding to the API of python-gitlab.  You should start this in a new branch and tag it for 6.1 when it's ready.  I'll add it if I ever need this functionality but for now I'm still working on other things in my corporate setup.

**Comment by samrocketman** [comment]
According to the [gitlabhq CHANGELOG](https://github.com/gitlabhq/gitlabhq/blob/6-1-stable/CHANGELOG#L6-L7) group membership has been added to the API as well.

```
  - API: Sudo api calls (Izaak Alpert)
  - API: Group membership api (Izaak Alpert)
```

**Comment by Itxaka** [comment]
Will have a look tomorrow, thanks for the heads up!

**Comment by Itxaka** [comment]
basic support is on, gotta check deeper and try testing it a bit, but in a couple of tests is working.

**Comment by samrocketman** [comment]
Cool I looked at your code but haven't tested it myself.  I'm still currently running at 9c5e375599a6d89ab1f4520224f47b43b40bcf9b.

**Comment by Itxaka** [comment]
Tested again, it does not work. Gives a 500 error if no sudo= is passed along.
A fix is to check like this:

``` python
        params = {'page': page, 'per_page': per_page}
        if sudo != "":
            params['sudo'] = sudo
```

Will try to fix it tomorrow

**Comment by samrocketman** [comment]
@Itxaka I would probably label this as a feature or enhancement rather than a bug.  It is something that didn't previously exist as opposed to implemented functionality the is not working correctly under certain conditions.

**Comment by Itxaka** [comment]
True. I labeled as both, for historic purpouses.
