### ISSUE TITLE
Separate the library into smaller parts

### ISSUE THREAD

**Issue by Itxaka** [pyapi-gitlab/pyapi-gitlab#35]
Having so many functions into one class and one file is kind of ugly and it goes against PEP (too many functions for a class I believe). 

We need to check if its viable to split it in several classes so you import what you need (from gitlab import projects for example)

**Comment by samrocketman** [comment]
@Itxaka I'm curious, why the name change?  I realize this is OT but I'm not sure how to contact you off list.

**Comment by Itxaka** [comment]
Hey @sag47 ,
it is because there is another project with the same name, on github and on Pypi, so the name was colliding in both places. Plus thanks to automated services, the docs from this project appeared on several webs as docs of the other project, which I guess was quite disturbing for the users of the other project.

Still, I don't like i-python-gitlab at ALL! It sounds pretty bad. Got any name suggestions? :smile:

**Comment by samrocketman** [comment]
pyapi-gitlab ("Pie-Aye-Pee-Eye-GitLab")?  It flows phonetically a little better.  Good job on keeping up with API functionality as best you can.  I understand GitLab has a fairly fast dev and release cycle.  Which is both awesome and a burden.

**Comment by Itxaka** [comment]
Sounds good! Ill try to change it today, sounds much better

**Comment by Itxaka** [comment]
closing this :D
