### ISSUE TITLE
GitLab 6.2 release API changes

### ISSUE THREAD

**Issue by samrocketman** [pyapi-gitlab/pyapi-gitlab#42]
It's that time again... API changes in the [new 6.2 release](https://github.com/gitlabhq/gitlabhq/blob/6-2-stable/CHANGELOG).  Namely:

```
  - Added search for projects by name to api (Izaak Alpert)
  - API: Remove group
  - API: Remove project
```

Also, not sure why it isn't in the `CHANGELOG` but but according to a [blog post](http://blog.gitlab.org/gitlab-ce-6-dot-2-released/) `Feature: Download repo archive (Izaak Alpert)` has been added as well.

**Comment by Itxaka** [comment]
oh god, this guys never stop! :D

Thanks for the heads up, will try updating it this weekend.

**Comment by agb80** [comment]
I'm getting this error trying to use with gitlibar-mirrors:

```
AttributeError: 'Gitlab' object has no attribute 'getGroups'
```

do you think that is because I'm running 6.2?

**Comment by Itxaka** [comment]
@agb80 which version of pyapi-gitlab are you using? the one that comes with gitlab-mirrors or did you update it via git/pip?

If it's the latest one from git/pip getGroups has been renamed to getgroups instead. If it's the one with gitlab-mirrors....than I have no idea, could you post more code (how you call it the method, for example) so I can have a look at it?

Thanks!

**Comment by agb80** [comment]
@Itxaka seems is a problem with the pyapi-gitlab included on gitlab-mirrors, I will check it with @sag47 and let you know. Thanks

**Comment by samrocketman** [comment]
@agb80 If you followed my install instructions for checking out the specific version of pyapi-gitlab then you wouldn't have encountered that issue.  In any case I'm encountering other bugs in the latest pyapi-gitlab.  It would have been better for you to open a new issue rather than hijack this one.

**Comment by samrocketman** [comment]
@agb80 I just updated gitlab-mirrors and it fixes your no attribute error.  See the development branch.  There isn't a stable release of gitlab-mirrors yet which addresses the latest pyapi-gitlab.  You can open an issue in my project so that we can track it and better communicate.

**Comment by jproffitt** [comment]
I believe the PR I did added all the Gitlab 6.2 stuff. (along with some stuff thats been around for a while, like notes) Can we close this task?

**Comment by Itxaka** [comment]
Sure, good work!
