### ISSUE TITLE
Host, User, and Token are required

### ISSUE THREAD

**Issue by samrocketman** [pyapi-gitlab/pyapi-gitlab#44]
```
git = gitlab.Gitlab("our_gitlab_host", token="mytoken")
```

That no longer works with the latest 6.1 branch of pyapi-gitlab.  Now at a minimum `host` and `user` are required with `token` being optional (see [source](https://github.com/Itxaka/pyapi-gitlab/blob/6.1/gitlab/__init__.py#L16)).  

Is that intended?  Should I update the documentation and pull request?  I honestly think the old behavior was fine because it works just fine with just a `host` and `token`.  Now you require `user` to be in the mix.

**Comment by samrocketman** [comment]
@Itxaka Can you create a "development" branch so that I can send you pull requests to that instead of your `6.1` stable branch?  User is not required.

**Comment by samrocketman** [comment]
d5317f3b509f859086a20a30544f313c41fcaf70 introduces this bug. This bug was introduced when you added sudo initially.

**Comment by Itxaka** [comment]
I see. This was a initial workaround for using sudo. I needed an username in case sudo was empty, but later changed the way sudo is called so the user  during init should not be required anymore, only if calling the login method.
