### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by waghanza** [pyapi-gitlab/pyapi-gitlab#64]
Hi,

I have installed the latest version of **gitlab**, `6.6.5`. In order to migrate from a gitolite to my fresh gitlab installation, I want to use the API to create my git repositories.

For this I've made a little `python` script

``` python
#!/usr/bin/env python

import gitlab
git.Gitlab("http://gitlab.domain.com", token="XXX")
```

and I have a error :

``` python
Traceback (most recent call last):
  File "/tmp/gitlab.py", line 6, in <module>
    from gitlab import Gitlab
  File "/tmp/gitlab.py", line 6, in <module>
    from gitlab import Gitlab
ImportError: cannot import name Gitlab
```

I never had this error on a python script. Do anybody has a idea of what's going on ?

Regards,

**Comment by Itxaka** [comment]
Hello,

This code is not correct:

```
git.Gitlab("http://gitlab.domain.com", token="XXX")
```

You should be doing:

```
git = gitlab.Gitlab("our_gitlab_host", token="mytoken")
```

and then use the git object

**Comment by waghanza** [comment]
sorry, wrong copy/paste

my script

``` python
#!/usr/bin/env python

import gitlab
import sys

git = gitlab.Gitlab("http://gitlab.domain.com", token="XXX")
```

Traceback 

``` python
  File "/tmp/gitlab.py", line 6, in <module>
    import gitlab 
  File "/tmp/gitlab.py", line 9, in <module>
    git = gitlab.Gitlab("http://192.168.21.19", token="kaFHncVFJPQyeepHqnpG")
```

Even ruby library https://github.com/NARKOZ/gitlab seems to fail ...

**Comment by Itxaka** [comment]
Hello,

are you calling your python file gitlab.py? Maybe it's a namespace issue, as it tries to import from gitlab.
Change the file name to whatever.py and try again, or bring the interactive console and do

```
import gitlab
print gitlab
```

That should not fail, post the output here.

**Comment by waghanza** [comment]
``` python
>>> import gitlab
>>> print gitlab
<module 'gitlab' from '/usr/lib/python2.7/site-packages/gitlab/__init__.pyc'>
```

This error is solved. I do not know why, by python interractive shell try to load `gitlab.py` in current dir ...
