### ISSUE TITLE
TLS/SSL support broken

### ISSUE THREAD

**Issue by dialt0ne** [pyapi-gitlab/pyapi-gitlab#65]
This commit https://github.com/Itxaka/pyapi-gitlab/commit/618e184b3c09b035023f6ec8b8921f92cc011751 forces the gitlab url to be HTTP only instead of HTTPS

**Comment by Itxaka** [comment]
Oh wow, good catch! Will try to fix it asap!

**Comment by Itxaka** [comment]
Should be fixed, thanks again for the catch!

**Comment by dialt0ne** [comment]
Confirmed! :thumbsup: Thanks for the quick turnaround. :smile: :clap:
