### ISSUE TITLE
verify_ssl parameter not passed to get/post requests

### ISSUE THREAD

**Issue by ghost** [pyapi-gitlab/pyapi-gitlab#66]
Dear users (and maintainer ;) ),

I'm using the wrapper script in combination with a (self-signed certiticate) gitlab instance:

``` python
git = gitlab.Gitlab("gitlab-instance-url", token="my-token", verify_ssl=False)
```

It works with a few methods, but not when using e.g. the _wall methods. For example the *getissuewallnotes_ method:

``` python
request = requests.get(self.projects_url + "/" + str(project_id) + "/issues/" + str(issue_id) + "/notes", headers=self.headers)
```

Compared to the _getprojectissue_ method, the _verify=self.verify_ssl_ option is _not_ passed. I changed the _getissuewallnotes_ method to:

``` python
request = requests.get(self.projects_url + "/" + str(project_id) + "/issues/" + str(issue_id) + "/notes", headers=self.headers, verify=self.verify_ssl)
```

And everything works fine. There are a few more methods, where the verify option won't be passed like _getsnippetwallnotes_ or _getmergerequestwallnotes_. I just want to report that issue.

Stefan

**Comment by Itxaka** [comment]
Good catch!

Im looking at it right now, will hopefully have a patch in a couple of hours.

Thanks! :+1:
