### ISSUE TITLE
Custom Access Levels for Groups

### ISSUE THREAD

**Issue by liaoarden** [pyapi-gitlab/pyapi-gitlab#68]
So right now it seems that access levels for groups are hardcoded to only support the official gitlab access levels, would it be possible to add in support for custom access levels like so:

```
def addgroupmember(self, groupid, user_id, access_level, sudo="", custom=10):
    ...
    elif access_level.lower() == "guest":
        access_level = 10
    else:
        access_level = custom
```

**Comment by Itxaka** [comment]
Closing this as the commit was closed and never updated
