### ISSUE TITLE
Duplicated effort?

### ISSUE THREAD

**Issue by gpocentek** [pyapi-gitlab/pyapi-gitlab#8]
Hi,

I've started my own python-gitlab project a while ago, maybe we could see if things can be merged?

https://github.com/gpocentek/python-gitlab

**Comment by Itxaka** [comment]
Hi @gpocentek !

Wow I didn't knew there was another wrapper! As I saw only a couple of wrapper in the documentation I assumed there was no wrapper for python.

Sure we could see of integrating both projects into one, I'll have a look at your code this weekend.

Cheers!

**Comment by Itxaka** [comment]
Hi again @gpocentek,

after checking both project, way too much work would be involved into merging them and unfortunately I don't have that kind of time to do it :(

Cheers anyway :D
