### ISSUE TITLE
Is there a way to push to repos using the api?

### ISSUE THREAD

**Issue by avckp** [pyapi-gitlab/pyapi-gitlab#80]
I have a gitlab instance running. I can get the repo/project details using the api. But how can I push directly to the repo using the API? Has it been implemented?
I have been through the docs but have not found anything.

**Comment by Itxaka** [comment]
Nope, that is git stuff. pyapi gitlab is mre oriented to management of the Gitlab stuff than the git commonds below it. 

For something like that you con use something like GitPython.

**Comment by avckp** [comment]
Ok.
Thanks for pointing to GitPython.
