### ISSUE TITLE
JSON response from createissue is discarded

### ISSUE THREAD

**Issue by GABeech** [pyapi-gitlab/pyapi-gitlab#83]
The `createissue` function discards the returned json and only returns true or false. 

This makes it much harder to work on an issue you just created via a script. 

If you change: 

``` python
 if request.status_code == 201:
            return True
        else:

            return False
```

to: 

``` python
 if request.status_code == 201:
            return json.loads(request.content.decode("utf-8"))
        else:

            return False
```

It would allow a script to work on a created issue immediately instead of having to try and figure out what the ID of the new issue is.

**Comment by Itxaka** [comment]
:+1:
