### ISSUE TITLE
Security of API calls

### ISSUE THREAD

**Issue by avckp** [pyapi-gitlab/pyapi-gitlab#88]
For any API call I need to attach a private_token and username as this

`GET http://example.com/api/v3/projects?private_token=QVy1PB7sTxfy4pqfZM1U&sudo=username`

Anybody snooping can find out the token username pair and cause havoc.
This can be fixed by restricting the domains from which API requests are handled by the git server.
Is there more elegant way of doing this? Am I missing something in the API?

**Comment by Itxaka** [comment]
You could use https to encrypt the communications. Anyway, this is a problem that comes from the Gitlab API in any case, and IIRC any API out there kind of uses the same thing, be it on the url or as an http header. I don't think there is a lot I can do from the python bindings to the Gitlab API.
