### ISSUE TITLE
Add new version to PIP

### ISSUE THREAD

**Issue by arruda** [pyapi-gitlab/pyapi-gitlab#93]
Bump the version, and add it to PIP... there are already 70+ commits of features since last version (6.3.2).

**Comment by Itxaka** [comment]
True. I was waiting to have some more time and getting it to par with the latests api versions of gitlab. Let

**Comment by Itxaka** [comment]
New version will come shortly as I add more tests and find any missing  methods.

**Comment by arruda** [comment]
\o/

**Comment by tonicmuroq** [comment]
I have the same request... and now looking forward for this...

**Comment by Itxaka** [comment]
Almost there! \o/

**Comment by arruda** [comment]
Yeah! please let us now when it's out =)

**Comment by Itxaka** [comment]
@arruda @tonicbupt 

Release is out! Available on pip and on github under the v7.5.0 tag. 

Make sure to read the README.md as there are quite a few breaking changes that are necessary so its easier to maintain and develop further.

**Comment by arruda** [comment]
Thanks @Itxaka =)
